services:
  web:
    build: .
    container_name: nokia-webem-generator
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
    restart: unless-stopped 