services:
  web:
    build: .
    container_name: nokia-webem-generator
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./generated:/app/generated
    env_file:
      - ./.env
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: nokia-webem-frontend
    ports:
      - "3000:80"
    depends_on:
      - web
    restart: unless-stopped
